# Generated by Django 4.1.7 on 2023-02-26 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('id_computer', models.CharField(max_length=20)),
                ('id_monitor', models.CharField(max_length=20)),
                ('anydesk', models.CharField(max_length=20)),
                ('swi', models.PositiveBigIntegerField()),
                ('puert', models.PositiveIntegerField()),
                ('ip', models.CharField(max_length=20)),
            ],
        ),
    ]
