# Generated by Django 4.1.7 on 2023-02-20 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('id_computer', models.CharField(max_length=20)),
                ('id_monitor', models.CharField(max_length=20)),
                ('switch', models.PositiveIntegerField()),
                ('puert', models.PositiveIntegerField()),
                ('ip', models.PositiveIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Company',
        ),
    ]
