# Generated by Django 4.1.7 on 2023-02-20 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_computer_delete_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='anydesk',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
