# Generated by Django 4.1.7 on 2023-02-20 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_computer_anydesk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='ip',
            field=models.CharField(max_length=20),
        ),
    ]
