# Generated by Django 4.1.7 on 2023-02-23 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_computer_ip'),
    ]

    operations = [
        migrations.RenameField(
            model_name='computer',
            old_name='switch',
            new_name='swi',
        ),
    ]
