# Generated by Django 4.1.7 on 2023-02-24 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_switch_computer_swi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Swi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='computer',
            name='swi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.swi'),
        ),
    ]
